### ISSUE TITLE
误删空格的小bug

### ISSUE THREAD

**Issue by QiChenX** [laorange/paper-assistant#1]
当完整英文文本中出现单引号‘的时候，生成的文本会把’后的空格删掉。
例如：
原文本：We compare test suites written by the systems’ developers.
新文本：We compare test suites written by the systems’developers.
systems'后的空格被误删了。

**Comment by laorange** [comment]
感谢反馈😊

例子中
`We compare test suites written by the systems’ developers.` 
可看出 `’` 并非英文的单引号

解决方案：将 `’` 换成 `'`: 
`We compare test suites written by the systems' developers.` 
可看到预想的输出。

---

为了解决类似的需求，将会更新：
+ 将英文标点转为中文标点
+ 将中文标点转为英文标点
