### ISSUE TITLE
为什么上传到服务器解压到根目录以后访问域名什么都不显示

### ISSUE THREAD

**Issue by yangsong888** [laorange/paper-assistant#10]
如题，

**Comment by laorange** [comment]
> 上传到服务器  &  解压到根目录

上传和解压了什么：
- [ ] 主分支上的源代码 ?
- [ ] [gh-pages](https://github.com/laorange/paper-assistant/tree/gh-pages) 分支上的编译后文件 ?
- [ ] [Release页面](https://github.com/laorange/paper-assistant/releases) 下的 `.zip` 文件 ?
- [ ] B站评论区下的[**离线资源**](https://laorange.lanzouw.com/b041kdw8j) ?

**Comment by yangsong888** [comment]
code/
![image](https://user-images.githubusercontent.com/40128378/221340001-a6b73844-a958-4cc8-be44-0e4016d3b765.png)
上传解压了code里的zip文件，

**Comment by laorange** [comment]
那只是开发环境下的源代码，需要编译后才可部署到服务器。

你可以选择：
+ 部署 [gh-pages](https://github.com/laorange/paper-assistant/tree/gh-pages) 分支上的编译后文件；
+ 部署 [Release页面](https://github.com/laorange/paper-assistant/releases) 下的 `.html` 文件；
+ 解压并部署B站评论区下的[**离线资源**](https://laorange.lanzouw.com/b041kdw8j)；
+ 构建npm环境，编译后再进行部署。

目前我是通过GitHub Page部署网页，因此你也可以Fork项目后，在 `Settings` - `Page` 中配置页面。

> 提示：如需修改代码，请留意该项目的开源协议为 `AGPL-3.0`。
