### ISSUE TITLE
在 Microsoft Edge Dev 115.0.1866.1 上发生布局错乱

### ISSUE THREAD

**Issue by PikaPikaPika97** [laorange/paper-assistant#13]
![image](https://github.com/laorange/paper-assistant/assets/85103436/f73f7b2c-5e8d-4135-92ef-5d06b3af042e)
如图所示，在使用egde dev打开时，会发生布局错乱，无法正常使用。

**Comment by laorange** [comment]
目前我用的是Edge正式版的113.0.1774.57，从未出现过这样的情况；我这里暂时无法复现出这个bug；建议检查是否受到其他浏览器插件的影响；期待进一步的信息。

**Comment by PikaPikaPika97** [comment]
关闭所有插件后依然会布局错乱，回到正式版后是正常的，这可能时edge dev的bug，先回到正式版使用啦，感谢。
