### ISSUE TITLE
请问怎么部署

### ISSUE THREAD

**Issue by ssln5014** [laorange/paper-assistant#2]
rt
想用自己的域名

**Comment by laorange** [comment]
目前我是通过GitHub Page部署网页，因此你可以Fork项目后，在 `Settings` - `Page` 中进行配置。

如果是想要部署于自己的服务器，可前往 [gh-pages分支](https://github.com/laorange/paper-assistant/tree/gh-pages) 并下载全部内容。

> 提示：如需修改代码，请留意该项目的开源协议为 `AGPL-3.0`。
