### ISSUE TITLE
移植到utools插件

### ISSUE THREAD

**Issue by swjqq** [laorange/paper-assistant#21]
将此项目的 **文本复制工具** 移植到 utools 插件，即 [utools-paper-assistant](https://github.com/swjqq/utools-paper-assistant)。

**Comment by laorange** [comment]
很早之前评论区中就有小伙伴建议迁移到utools插件中🤣我不是utools用户，确实没有动力再去开发

🫡我在README中加了推荐链接，这个插件是强有力的补充！
