### ISSUE TITLE
输入全角括号时候会改为半角括号

### ISSUE THREAD

**Issue by MinamiyamaHokuto** [laorange/paper-assistant#8]
如题，即使不开中文符号转英文符号也会有这个情况；甚至开了英文符号转中文符号还是会有这个情况。

**Comment by MinamiyamaHokuto** [comment]
例如

- 原文：此时，就需对图像进行增强（平滑）处理。

- 处理后：此时，就需对图像进行增强(平滑) 处理。

并且在括号括回出还多了一个空格。

**Comment by laorange** [comment]
这是因为**功能设置**中默认打开了"全角字符转半角字符"，目前全角括号也被算入到全角符号的集合中了，将在下次更新时优化

**Comment by laorange** [comment]
英文右括号多出一个空格是考虑在英文句子中需要这样一个空格，是**在标点符号后添加空格**功能的生效结果，暂未想好该功能的优化方向

**Comment by MinamiyamaHokuto** [comment]
> 英文右括号多出一个空格是考虑在英文句子中需要这样一个空格，是**在标点符号后添加空格**功能的生效结果，暂未想好该功能的优化方向

标点符号后添加空格是西文符号习惯，如果全角括号未来被视作符号了应该能够解决。如：

- 原文全角括号+中文不增加括号后空格，如”增强（平滑）处理“；处理后”增强（平滑）处理“。（不变）
- 原文半角括号+英文增加括号后空格，如”I am a GitHub(a website)user.“，匹配`^[a-zA-Z0-9]+\(`和`^[a-zA-Z0-9]+\)`，使之变为”I am a GitHub (a website) user.“
